
package api.client.doranco;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StoreService", targetNamespace = "http://service.doranco.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StoreService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://service.doranco.com/", className = "api.client.doranco.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.doranco.com/", className = "api.client.doranco.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        StoreDTO1 arg0);

}
